// src/pages/Alerts.jsx
import { useState, useEffect } from 'react'
import { doc, updateDoc } from 'firebase/firestore'
import { db, subscribeAlerts } from '../services/firebase'
import { severityStyle, formatTimestamp, TAG_COLORS } from '../utils/helpers'

function Tag({ label }) {
  const color = TAG_COLORS[label] || '#64748B'
  return (
    <span style={{
      fontSize: 9, padding: '2px 7px', borderRadius: 3,
      background: `${color}18`, color, border: `1px solid ${color}30`,
      letterSpacing: '0.08em', textTransform: 'uppercase',
      fontFamily: "'IBM Plex Mono', monospace",
    }}>{label}</span>
  )
}

export default function Alerts() {
  const [alerts, setAlerts] = useState([])
  const [filter, setFilter] = useState('all') // all | unread

  useEffect(() => {
    return subscribeAlerts(setAlerts)
  }, [])

  async function markRead(id) {
    await updateDoc(doc(db, 'alerts', id), { read: true })
  }

  async function markAllRead() {
    await Promise.all(
      alerts.filter(a => !a.read).map(a => updateDoc(doc(db, 'alerts', a.id), { read: true }))
    )
  }

  const shown = filter === 'unread' ? alerts.filter(a => !a.read) : alerts
  const unreadCount = alerts.filter(a => !a.read).length

  return (
    <div style={{ padding: '28px 32px', fontFamily: "'IBM Plex Mono', monospace", color: '#E2E8F0' }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 28 }}>
        <div>
          <div style={{ fontSize: 10, color: '#374151', letterSpacing: '0.18em', textTransform: 'uppercase', marginBottom: 4 }}>
            Auto-generated by Firebase
          </div>
          <h1 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: '#F9FAFB' }}>
            Alert Center
            {unreadCount > 0 && (
              <span style={{
                marginLeft: 12, fontSize: 12, padding: '3px 10px', borderRadius: 10,
                background: 'rgba(255,68,68,0.15)', border: '1px solid rgba(255,68,68,0.3)',
                color: '#FF4444',
              }}>
                {unreadCount} unread
              </span>
            )}
          </h1>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          {['all', 'unread'].map(f => (
            <button key={f} onClick={() => setFilter(f)} style={{
              padding: '7px 14px', borderRadius: 6, cursor: 'pointer',
              background: filter === f ? 'rgba(255,68,68,0.1)' : 'transparent',
              border: filter === f ? '1px solid rgba(255,68,68,0.3)' : '1px solid #1F2937',
              color: filter === f ? '#FF6B6B' : '#4B5563',
              fontSize: 11, fontFamily: "'IBM Plex Mono', monospace",
              textTransform: 'capitalize',
            }}>{f}</button>
          ))}
          {unreadCount > 0 && (
            <button onClick={markAllRead} style={{
              padding: '7px 14px', borderRadius: 6, cursor: 'pointer',
              background: 'transparent', border: '1px solid #1F2937',
              color: '#4B5563', fontSize: 11, fontFamily: "'IBM Plex Mono', monospace",
            }}>
              Mark all read
            </button>
          )}
        </div>
      </div>

      {shown.length === 0 ? (
        <div style={{
          background: '#0B1118', border: '1px solid #0F1923', borderRadius: 10,
          padding: '60px 20px', textAlign: 'center', color: '#1F2937', fontSize: 13,
        }}>
          {filter === 'unread' ? 'No unread alerts' : 'No alerts yet — Critical threats (score ≥ 80) auto-create alerts'}
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {shown.map(alert => {
            const sev = severityStyle(alert.severity)
            return (
              <div key={alert.id} style={{
                background: '#0B1118',
                border: `1px solid ${alert.read ? '#0F1923' : sev.border}`,
                borderRadius: 10, padding: '16px 20px',
                opacity: alert.read ? 0.6 : 1,
                transition: 'all 0.2s',
                position: 'relative',
              }}>
                {!alert.read && (
                  <div style={{
                    position: 'absolute', top: 16, right: 16,
                    width: 7, height: 7, borderRadius: '50%',
                    background: '#FF4444', boxShadow: '0 0 8px #FF4444',
                  }} />
                )}
                <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
                  <span style={{
                    fontSize: 11, padding: '3px 9px', borderRadius: 4,
                    background: sev.bg, color: sev.color, border: `1px solid ${sev.border}`,
                  }}>{alert.severity}</span>
                  <span style={{ fontSize: 14, fontWeight: 700, color: '#F1F5F9', fontFamily: 'monospace' }}>
                    {alert.ip}
                  </span>
                  <span style={{ fontSize: 12, color: '#FF4444', fontWeight: 700 }}>
                    Score: {alert.riskScore}
                  </span>
                </div>
                <div style={{ fontSize: 12, color: '#6B7280', marginBottom: 10 }}>{alert.message}</div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <div style={{ display: 'flex', gap: 5 }}>
                    {(alert.tags || []).map(t => <Tag key={t} label={t} />)}
                    {alert.countryCode && (
                      <span style={{ fontSize: 10, padding: '2px 7px', borderRadius: 3, background: '#0F1923', color: '#374151' }}>
                        {alert.countryCode}
                      </span>
                    )}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <span style={{ fontSize: 10, color: '#374151' }}>
                      {formatTimestamp(alert.createdAt)}
                    </span>
                    {!alert.read && (
                      <button onClick={() => markRead(alert.id)} style={{
                        fontSize: 10, padding: '3px 10px', borderRadius: 5, cursor: 'pointer',
                        background: 'transparent', border: '1px solid #1F2937',
                        color: '#374151', fontFamily: "'IBM Plex Mono', monospace",
                      }}>
                        Dismiss
                      </button>
                    )}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
